// This is a Javascript test harness that simulates the execution of Lambda function code
// From the command prompt, type "node test.js"

const MyLambdaFunction = require('../custom/index.js'); 

 // this is the Lambda request data, generated by the Alexa service.
let event =
{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.9e0f5639-44ea-41aa-a23d-84c4d55af4d1",
		"application": {
			"applicationId": "amzn1.ask.skill.333ebe7a-907d-46bc-922c-757277bf3e2e"
		},
		"user": {
			"userId": "amzn1.ask.account.AEXODP3HJ2EED3UOF7EJEB5ZZSUISD46VOCXBWFTSCTNRKQ6VVXU2CKBRR3WKF7ZKEVOWB4DAWKSZTCJYN4MAJP7XLCCA75FPTUTHPTBNIZ5J7SKIBWNDZBTDWUX6BN72RUPWZDS74R6F4KUDF7T62QVQODKKN45Z3FNACDI5O4CWPTX3U5SSTWHYZENI23LSLXJVQST6IWKRLY"
		}
	},
	"context": {
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.333ebe7a-907d-46bc-922c-757277bf3e2e"
			},
			"user": {
				"userId": "amzn1.ask.account.AEXODP3HJ2EED3UOF7EJEB5ZZSUISD46VOCXBWFTSCTNRKQ6VVXU2CKBRR3WKF7ZKEVOWB4DAWKSZTCJYN4MAJP7XLCCA75FPTUTHPTBNIZ5J7SKIBWNDZBTDWUX6BN72RUPWZDS74R6F4KUDF7T62QVQODKKN45Z3FNACDI5O4CWPTX3U5SSTWHYZENI23LSLXJVQST6IWKRLY"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AGCVWMCWTOE7NUEWHJYWSDCTJGUR4QOFCS6R4A4LOD3KIEFOBWJAHKVIFP5VPDXGITJ2BBKCE6BGQWRNSXR3SK6Z25E3FVANVOWYHHA6D2U2VDEDUTW3KTU6FULKPBI5PISL6FNZ7TA2OSPOH4RT3VHKPBU2J3LYKM4AREMGGON3XHAPTMDE2",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjMzM2ViZTdhLTkwN2QtNDZiYy05MjJjLTc1NzI3N2JmM2UyZSIsImV4cCI6MTU0NTM5MDkxNSwiaWF0IjoxNTQ1Mzg3MzE1LCJuYmYiOjE1NDUzODczMTUsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUdDVldNQ1dUT0U3TlVFV0hKWVdTRENUSkdVUjRRT0ZDUzZSNEE0TE9EM0tJRUZPQldKQUhLVklGUDVWUERYR0lUSjJCQktDRTZCR1FXUk5TWFIzU0s2WjI1RTNGVkFOVk9XWUhIQTZEMlUyVkRFRFVUVzNLVFU2RlVMS1BCSTVQSVNMNkZOWjdUQTJPU1BPSDRSVDNWSEtQQlUySjNMWUtNNEFSRU1HR09OM1hIQVBUTURFMiIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFFWE9EUDNISjJFRUQzVU9GN0VKRUI1WlpTVUlTRDQ2Vk9DWEJXRlRTQ1ROUktRNlZWWFUyQ0tCUlIzV0tGN1pLRVZPV0I0REFXS1NaVENKWU40TUFKUDdYTENDQTc1RlBUVVRIUFRCTklaNUo3U0tJQldORFpCVERXVVg2Qk43MlJVUFdaRFM3NFI2RjRLVURGN1Q2MlFWUU9ES0tONDVaM0ZOQUNESTVPNENXUFRYM1U1U1NUV0hZWkVOSTIzTFNMWEpWUVNUNklXS1JMWSJ9fQ.MASPJsfkc-tRe238LhQ7_GPkn53WgnH-mD9ZUbCEneXr43_m0CP0F6BDEHn3kI1xzOCaQOkBhdYhLgfUk5YyDMRqQkM4Uek1CmHK8Lx6Md_HoyKKznsIMFcf_98lojNbDhGA7uPD_6q_JRo2tQErTFRvS4CNXI1fA9xAid1fdgXLK6jY1TYmvWmankLRiU27SsP-TYOk7IeMAQ6dPDSpRfz5dECSTXwJjHmsxeKuwXMKZPeW1PjnBv5e04rqfqavgzHfUzuVpLZezlT40LU3sBPI1uzuxvVbGsGbUm9Zwr8gjKipFyMYHqqPzLww4GUDHrvvdvusEqW5jqb1RfujGg"
		},
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			]
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.d55b4ea5-7112-4a9b-82d8-7a6f3bfabdf6",
		"timestamp": "2018-12-21T10:15:15Z",
		"locale": "en-US",
		"intent": {
			"name": "PullRequestIntent",
			"confirmationStatus": "NONE",
			"slots": {
				"repository": {
					"name": "repository",
					"value": "react-loopback-generator",
					"confirmationStatus": "NONE",
					"source": "USER"
				}
			}
		}
	}
};

let context = {
    'succeed': function (data) {
        console.log(JSON.stringify(data, null,'\t') );

    },
    'fail': function (err) {
        console.log('context.fail occurred');
        console.log(JSON.stringify(err, null,'\t') );
    }

};

function callback(error, data) {
    if(error) {
        console.log('error: ' + error);
    } else {
        console.log(data);
    }
}

// call the function
MyLambdaFunction['handler'] (event, context, callback);
